### ISSUE TITLE
refactor: 사이드바 컴포넌트 새로 만들기

### ISSUE THREAD

**Issue by hyundonny** [hyundonny/swit-messenger#2]
# TASK CARD

Task Description : 
디자인적으로나, 기능적인 면에서 현재 만들어둔 사이드바가 부족하다고 느껴진다. 작은 화면에서 보며 만들었더니 큰 화면일 때 내가 생각했던 것과 다르게 나오는 문제가 있다. 따라서, 큰 화면에서도 디자인을 고쳐볼 필요가 있다. 뿐만 아니라, 지금은 position absolute를 써서 모바일 화면일때는 화면 밖에 나가있고, 큰 화면일때 다시 화면 안으로 이동하도록 구현했는데, swit 웹사이트를 뜯어보니 width를 활용해서 사이드바를 구현했다. 비슷한 방식으로 구현해보는 것도 재밌을 것 같다.

Date : 2022-03-27

## to-do

- [x] 사이드바 디자인을 피그마로 구현해 정확히 뭘 구현하려는 건지 정리하기
- [x] 사이드바 메인 컨텐츠 (메시지/채널 또는 연락처) 별로 따로 구현하기
- [x] media query와 width 활용해서 모바일 화면에서는 사라지고, 데스크탑 화면에서는 나타나는 사이드바 구현하기
